NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.retailer.foodtrace.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.retailer.foodtrace.com-cert.pem
    OrganizationalUnitIdentifier: peer
