NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.supplier.foodtrace.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.supplier.foodtrace.com-cert.pem
    OrganizationalUnitIdentifier: peer
